### PR TITLE
Feature - First Query Sprint

### PR DESCRIPTION
**Pull request by gjmistkawi**
Need to merge the first query sprint with stories:
288: Percentage of Fraud
287: Top 5 Transactions
286: Insufficient Balance
289: Top 5 by zipcode
293: Transactions by state
291: Transaction types
292: Top 10 largest Transactions

### CODE REVIEW

**Review by bartell-lin — COMMENTED** [review]
Try to use more descriptive variable instead of t or d.

**Review by bartell-lin — COMMENTED** [review]
Insufficient balance story
consider using an unordered_map instead of map for faster performance

**Review by bartell-lin — COMMENTED** [review]
Also consider using <execution> header for parallel sorts

**Comment by gjmistkawi** [comment]
> Also consider using header for parallel sorts

Still working on getting the execution library working within my system. Once that's up and running I'll add those changes in.

**Comment by gjmistkawi** [comment]
Changed map to unordered map.

**Pull request merged**
